### PR TITLE
Linear interpolation

### PR DESCRIPTION
**Pull request by t-mullen**
Draws straight lines between points. Not as sexy as bezier curves, but faster and probably looks equally good.

### CODE REVIEW

**Comment by RationalCoding** [comment]
Draws straight lines between points. Not as sexy as bezier curves, but faster and probably looks equally good.

**Comment by t-mullen** [comment]
#5

**Comment by t-mullen** [comment]
Dang you fast.

**Comment by t-mullen** [comment]
Seems a bit laggy during collab, going to see why.

**Comment by theiliad** [comment]
yeah it does get laggy

**Comment by theiliad** [comment]
it looks pretty good though

**Comment by t-mullen** [comment]
Ah, the CPU is choking since we aren't requesting animation frames. I'll fix it.

**Pull request merged**
